config/routes.rb
Rails.application.routes.draw do
  resources :equipamentos

  get 'equipamentos/autorizar/:id' => 'equipamentos#autorizar', as: 'equipamento_autorizar'
  # namespace :equipamentos do
  #   get 'autorizar'
  #   get 'desaltorizar'
  # end

  resources :tipo_equipamentos
  resources :tipo_documentos

  get 'prazos' => "registroprazos#index"
  get 'prazos/novo' => "registroprazos#new"

  resources :registroprazos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "tipo_documentos#home"
end

app/models/equipamento.rb
# == Schema Information
#
# Table name: equipamentos
#
#  id                  :bigint           not null, primary key
#  classificacao       :string
#  data_fim            :datetime
#  data_inicio         :datetime
#  descricao           :string
#  flag_classificacao  :string
#  geolocalizacao      :string
#  identificacao       :string
#  ip                  :string
#  mac                 :string
#  nome                :string
#  status              :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  tipo_equipamento_id :bigint
#
# Indexes
#
#  index_equipamentos_on_tipo_equipamento_id  (tipo_equipamento_id)
#
# Foreign Keys
#
#  fk_rails_...  (tipo_equipamento_id => tipo_equipamentos.id)
#

class Equipamento < ApplicationRecord
  belongs_to :tipo_equipamento, optional: true

  extend Enumerize
  extend ActiveModel::Naming

  enumerize :status, in: %w(autorizado nao_autorizado bloqueado movimentado recebido), i18n_scope: "equipamento.status", default: :nao_autorizado, predicates: true
  enumerize :classificacao, in: %w(movel fixo), i18n_scope: "equipamento.classificacao", predicates: true
  enumerize :flag_classificacao, in: %w(proprio institucional), i18n_scope: "equipamento.flag_classificacao", predicates: true

  has_paper_trail
end

app/controllers/equipamentos_controller.rb
# == Schema Information
#
# Table name: equipamentos
#
#  id                  :bigint           not null, primary key
#  classificacao       :string
#  data_fim            :datetime
#  data_inicio         :datetime
#  descricao           :string
#  flag_classificacao  :string
#  geolocalizacao      :string
#  identificacao       :string
#  ip                  :string
#  mac                 :string
#  nome                :string
#  status              :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  tipo_equipamento_id :bigint
#
# Indexes
#
#  index_equipamentos_on_tipo_equipamento_id  (tipo_equipamento_id)
#
# Foreign Keys
#
#  fk_rails_...  (tipo_equipamento_id => tipo_equipamentos.id)
#

class EquipamentosController < ApplicationController
  before_action :set_paper_trail_whodunnit

  before_action :set_equipamento, only: [:edit, :update, :destroy, :autorizar, :show]
  before_action :set_tipos, only: [:show, :new, :edit, :create, :update]
  before_action :set_classificacoes, only: [:new, :edit, :create, :update]
  before_action :set_flags_classificacao, only: [:new, :edit, :create, :update]

  # GET /equipamentos
  # GET /equipamentos.json
  def index
    @equipamentos = Equipamento.where(status: [:autorizado, :nao_autorizado, :bloqueado]).order(updated_at: :desc)
  end

  # GET /equipamentos/1
  # GET /equipamentos/1.json
  def show
  end

  # GET /equipamentos/new
  def new
    @equipamento = Equipamento.new
  end

  # GET /equipamentos/1/edit
  def edit
  end

  # POST /equipamentos
  # POST /equipamentos.json
  def create
    @equipamento = Equipamento.new(equipamento_params)

    if @equipamento.save
      if autorizar?
        redirect_to equipamento_autorizar_path(@equipamento)
      else
        respond_to do |format|
          format.html {redirect_to equipamentos_path, notice: 'Equipamento was successfully created.'}
          format.json {render :show, status: :created, location: @equipamento}
        end
      end
    else
      respond_to do |format|
        format.html {render :new}
        format.json {render json: @equipamento.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /equipamentos/1
  # PATCH/PUT /equipamentos/1.json
  def update
    if autorizar? and data_inicio? and data_fim?
      @equipamento.status = :autorizado
    end

    respond_to do |format|
      if @equipamento.update(equipamento_params)
        if @equipamento.status.autorizado?
          format.html {redirect_to equipamentos_path, notice: 'Equipamento autorizado com sucesso!'}
          format.json {render :show, status: :ok, location: @equipamento}
        else
          format.html {redirect_to equipamento_path, notice: 'Equipamento salvo com sucesso!'}
          format.json {render :show, status: :ok, location: @equipamento}
        end
      else
        format.html {render :edit}
        format.json {render json: @equipamento.errors, status: :unprocessable_entity}
      end
    end

    # respond_to do |format|
    #   if @equipamento.update(equipamento_params)
    #     format.html {redirect_to @equipamento, notice: 'Equipamento atualizado com sucesso!'}
    #     format.json {render :show, status: :ok, location: @equipamento}
    #   else
    #     format.html {render :edit}
    #     format.json {render json: @equipamento.errors, status: :unprocessable_entity}
    #   end
    # end
  end

  # DELETE /equipamentos/1
  # DELETE /equipamentos/1.json
  def destroy
    @equipamento.destroy
    respond_to do |format|
      format.html {redirect_to equipamentos_url, notice: 'Equipamento was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def autorizar
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_equipamento
    @equipamento = Equipamento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def equipamento_params
    params.require(:equipamento).permit(:nome,
                                        :descricao,
                                        :status,
                                        :tipo_equipamento_id,
                                        :classificacao,
                                        :flag_classificacao,
                                        :identificacao,
                                        :ip,
                                        :mac,
                                        :geolocalizacao,
                                        :data_inicio,
                                        :data_fim)
  end

  def set_tipos
    @tipos = TipoEquipamento.order(:nome)
  end

  def set_classificacoes
    @classificacoes = Equipamento.classificacao.options
  end

  def set_flags_classificacao
    @flags_classificacao = Equipamento.flag_classificacao.options
  end

  def autorizar?
    if params[:autorizar] == 'true'
      return true
    end
    false
  end

  def data_inicio?
    params[:equipamento]['data_inicio(3i)'].present? and
        params[:equipamento]['data_inicio(2i)'].present? and
        params[:equipamento]['data_inicio(1i)'].present? and
        params[:equipamento]['data_inicio(4i)'].present? and
        params[:equipamento]['data_inicio(5i)'].present?
  end

  def data_fim?
    params[:equipamento]['data_fim(3i)'].present? and
        params[:equipamento]['data_fim(2i)'].present? and
        params[:equipamento]['data_fim(1i)'].present? and
        params[:equipamento]['data_fim(4i)'].present? and
        params[:equipamento]['data_fim(5i)'].present?
  end

end

app/helpers/equipamentos_helper.rb
# == Schema Information
#
# Table name: equipamentos
#
#  id                  :bigint           not null, primary key
#  classificacao       :string
#  data_fim            :datetime
#  data_inicio         :datetime
#  descricao           :string
#  flag_classificacao  :string
#  geolocalizacao      :string
#  identificacao       :string
#  ip                  :string
#  mac                 :string
#  nome                :string
#  status              :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  tipo_equipamento_id :bigint
#
# Indexes
#
#  index_equipamentos_on_tipo_equipamento_id  (tipo_equipamento_id)
#
# Foreign Keys
#
#  fk_rails_...  (tipo_equipamento_id => tipo_equipamentos.id)
#

module EquipamentosHelper
end

app/views/equipamentos/_form.html.erb
<%= form_with(model: equipamento, local: true) do |form| %>
  <% if equipamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipamento.errors.count, "error") %> prohibited this equipamento from being saved:</h2>

      <ul>
        <% equipamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col m6">
      <%= form.label :tipo_equipamento_id %>
      <%= form.collection_select :tipo_equipamento_id, @tipos, :id, :nome, {prompt: '-- Selecione --'}, {class: "browser-default"} %>
    </div>
    <div class="col m3">
      <%= form.label :classificacao %>
      <%= form.select :classificacao, @classificacoes, {:prompt => '-- Selecione --'}, {class: 'browser-default'} %>
    </div>
    <div class="col m3">
      <%= form.label :flag_classificacao %>
      <%= form.select :flag_classificacao, @flags_classificacao, {:prompt => '-- Selecione --'}, {class: 'browser-default'} %>
    </div>
  </div>

  <br>
  <br>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :identificacao %>
    <%= form.text_field :identificacao %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="field">
    <%= form.label :mac %>
    <%= form.text_field :mac %>
  </div>

  <div class="field">
    <%= form.label :geolocalizacao %>
    <%= form.text_field :geolocalizacao %>
  </div>

  <button type="button" class="modal-trigger" href="#modal1">Salvar</button>

  <div id="modal1" class="modal col m6">
    <div class="modal-content">
      <h4>Deseja autorizar o equipamento cadastrado?</h4>
    </div>
    <div class="modal-footer">
      <div class="row center" style="height: 100%; overflow-y: hidden; overflow-x: hidden; width: inherit;">
        <%= form.button 'Sim', name: :autorizar, value: 'true', class: 'btn' %>
        <%= form.button 'Agora não', name: :autorizar, value: 'false', class: 'btn' %>
      </div>
    </div>
  </div>

<% end %>

app/views/equipamentos/autorizar.erb
<%= form_for @equipamento, method: :put do |form| %>
  <% if @equipamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipamento.errors.count, "error") %> prohibited this equipamento from being saved:</h2>

      <ul>
        <% @equipamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <h5 class="center">Autorizaçao do equipamento: <%= @equipamento.nome.truncate(45) %></h5>
  </div>

  <div class="row">
    <div class="col m3">
      <fieldset>
        <h6>Servidor responsável</h6>
      </fieldset>
    </div>
    <div class="col m3">
      <fieldset>
        <h6>Lotação do servidor responsável</h6>
      </fieldset>
    </div>

    <div class="col m3">
      <div class="field">
        <fieldset>
          <%= form.label :data_inicio %>
          <%= form.datetime_select :data_inicio %>
        </fieldset>
      </div>
    </div>
    <div class="col m3">
      <div class="field">
        <fieldset>

          <%= form.label :data_fim %>
          <%= form.datetime_select :data_fim %>
        </fieldset>
      </div>
    </div>
  </div>

  <%= form.button 'Autorizar', class: 'btn', name: :autorizar, value: 'true' %>
  <%= link_to 'Cancelar', equipamentos_path, class: 'btn'%>
<% end %>

app/views/equipamentos/edit.html.erb
<h1>Editing Equipamento</h1>

<%= render 'form', equipamento: @equipamento %>

<%= link_to 'Show', @equipamento %> |
<%= link_to 'Back', equipamentos_path %>

app/views/equipamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipamentos</h1>

<div class="right">
  <%= link_to 'Novo', new_equipamento_path %> <br>
  <%= link_to 'Monitorar (SECAD)', "#" %> <br>
  <%= link_to 'Movimentação de equipamentos', "#" %>
</div>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @equipamentos.each do |equipamento| %>
    <tr>
      <td><%= equipamento.nome %></td>
      <td><%= equipamento.status_text %></td>
      <td><%= link_to 'Visualizar', equipamento %></td>
      <% if equipamento.status.autorizado? %>
        <td><%= link_to 'Desaltorizar', '#' %></td>
      <% else %>
        <td><%= link_to 'Autorizar', equipamento_autorizar_path(equipamento), class: "inbox-sf-add-btn tip" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/equipamentos/index_movimentacao.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipamentos</h1>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @equipamentos.each do |equipamento| %>
    <tr>
      <td><%= equipamento.nome %></td>
      <td><%= equipamento.status_text %></td>
      <td><%= link_to 'Visualizar', equipamento %></td>
      <% if equipamento.status.movimentado? %>
        <td><%= button_to 'Receber equipamento movimentado', '#' %></td>
      <% else %>
        <td><%= button_to '', '#' %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/equipamentos/new.html.erb
<h1>Novo equipamento</h1>

<%= render 'form', equipamento: @equipamento %>

<%= link_to 'Voltar', equipamentos_path %>

app/views/equipamentos/show.html.erb
<p id="notice"><%= notice %></p>

<%# binding.pry %>
<fieldset>
  <h5 class="center">Equipamento</h5>
  <br>
  <p>
    <strong>Nome:</strong>
    <%= @equipamento.nome %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= @equipamento.descricao %>
  </p>


  <p>
    <strong>Tipo equipamento:</strong>
    <%= @equipamento.tipo_equipamento.nil? ? '' : @equipamento.tipo_equipamento.nome %>
  </p>

  <p>
    <strong>Classificacao:</strong>
    <%= @equipamento.classificacao %>
  </p>

  <p>
    <strong>Flag classificacao:</strong>
    <%= @equipamento.flag_classificacao %>
  </p>

  <p>
    <strong>Identificacao:</strong>
    <%= @equipamento.identificacao %>
  </p>

  <p>
    <strong>Ip:</strong>
    <%= @equipamento.ip %>
  </p>

  <p>
    <strong>Mac:</strong>
    <%= @equipamento.mac %>
  </p>

  <p>
    <strong>Geolocalizacao:</strong>
    <%= @equipamento.geolocalizacao %>
  </p>
</fieldset>
<br>

<%# if @equipamento.status.autorizado? %>

  <fieldset>
    <h5 class="center">Autorizaçao</h5>
    <br>
    <div class="row">
      <div class="col m6">
        <p>
          <strong>Status:</strong>
          <%= @equipamento.status_text %>
          <% if @equipamento.status.autorizado? %>
            <%= link_to 'Alterar autorização', '#' %>
          <% elsif @equipamento.status.nao_autorizado? %>
            <%= link_to 'Autorizar', '#' %>
          <% end %>
        </p>


      </div>
      <% if @equipamento.status.autorizado? %>
        <div class="col m6">
          <p>
            <strong>Data inicio:</strong>
            <%= @equipamento.data_inicio %>
          </p>

          <p>
            <strong>Data fim:</strong>
            <%= @equipamento.data_fim %>
          </p>
        </div>
      <% end %>
    </div>

  </fieldset>
<%# end %>

<%= link_to 'Alterar', edit_equipamento_path(@equipamento) %> |
<%= link_to 'Voltar', equipamentos_path %>