config/routes.rb
Rails.application.routes.draw do
  resources :equipamentos

  get 'equipamentos/autorizar/:id' => 'equipamentos#autorizar', as: 'equipamento_autorizar'
  # namespace :equipamentos do
  #   get 'autorizar'
  #   get 'desaltorizar'
  # end

  resources :tipo_equipamentos
  resources :tipo_documentos

  get 'prazos' => "registroprazos#index"
  get 'prazos/novo' => "registroprazos#new"

  resources :registroprazos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "tipo_documentos#home"
end

app/models/tipo_equipamento.rb
# == Schema Information
#
# Table name: tipo_equipamentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TipoEquipamento < ApplicationRecord
  validates :nome, presence: true, uniqueness: true, length: { maximum: 255}
  has_many :equipamentos
end

app/controllers/tipo_equipamentos_controller.rb
# == Schema Information
#
# Table name: tipo_equipamentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TipoEquipamentosController < ApplicationController
  before_action :set_tipo_equipamento, only: [:show, :edit, :update, :destroy]

  # GET /tipo_equipamentos
  # GET /tipo_equipamentos.json
  def index
    @tipo_equipamentos = TipoEquipamento.all
  end

  # GET /tipo_equipamentos/1
  # GET /tipo_equipamentos/1.json
  def show
  end

  # GET /tipo_equipamentos/new
  def new
    @tipo_equipamento = TipoEquipamento.new
  end

  # GET /tipo_equipamentos/1/edit
  def edit
  end

  # POST /tipo_equipamentos
  # POST /tipo_equipamentos.json
  def create
    @tipo_equipamento = TipoEquipamento.new(tipo_equipamento_params)

    respond_to do |format|
      if @tipo_equipamento.save
        format.html { redirect_to @tipo_equipamento, notice: 'Tipo equipamento was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_equipamento }
      else
        format.html { render :new }
        format.json { render json: @tipo_equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_equipamentos/1
  # PATCH/PUT /tipo_equipamentos/1.json
  def update
    respond_to do |format|
      if @tipo_equipamento.update(tipo_equipamento_params)
        format.html { redirect_to @tipo_equipamento, notice: 'Tipo equipamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_equipamento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_equipamentos/1
  # DELETE /tipo_equipamentos/1.json
  def destroy
    @tipo_equipamento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_equipamentos_url, notice: 'Tipo equipamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_equipamento
      @tipo_equipamento = TipoEquipamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_equipamento_params
      params.require(:tipo_equipamento).permit(:nome)
    end
end

app/helpers/tipo_equipamentos_helper.rb
# == Schema Information
#
# Table name: tipo_equipamentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TipoEquipamentosHelper
end

app/views/tipo_equipamentos/_form.html.erb
<%= form_with(model: tipo_equipamento, local: true) do |form| %>
  <% if tipo_equipamento.errors.any? %>
    <div id="error_explanation">
      <!-- <h2><%= pluralize(tipo_equipamento.errors.count, "error") %> prohibited this tipo_equipamento from being saved:</h2>-->

      <ul>
      <% tipo_equipamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn' %>
  </div>
<% end %>

app/views/tipo_equipamentos/edit.html.erb
<h1>Editing Tipo Equipamento</h1>

<%= render 'form', tipo_equipamento: @tipo_equipamento %>

<%= link_to 'Mostrar', @tipo_equipamento, class: 'btn' %> |
<%= link_to 'Cancelar', tipo_equipamentos_path, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn' %>

app/views/tipo_equipamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Equipamentos</h1>


<% if @tipo_equipamentos.length == 0 %>
  <h2>Não existem registros cadastrados</h2>
<% else %>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Data de Registro</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tipo_equipamentos.each do |tipo_equipamento| %>
        <tr>
          <td><%= tipo_equipamento.nome %></td>
          <td><%= tipo_equipamento.created_at.strftime('%d/%m/%Y') %></td>
          <td><%= link_to 'Visualizar', tipo_equipamento, class: 'btn' %></td>
          <td><%= link_to 'Alterar', edit_tipo_equipamento_path(tipo_equipamento), class: 'btn' %></td>
          <td><%= link_to 'Excluir', tipo_equipamento, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br>

<%= link_to 'Cadastrar tipo de equipamento', new_tipo_equipamento_path, class: 'btn' %>

app/views/tipo_equipamentos/new.html.erb
<h1>New Tipo Equipamento</h1>

<%= render 'form', tipo_equipamento: @tipo_equipamento %>

<%= link_to 'Voltar', tipo_equipamentos_path, class:"btn", data: { confirm: "Tem certeza que deseja voltar sem salvar?"} %>

app/views/tipo_equipamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tipo_equipamento.nome %>
</p>

<%= link_to 'Editar', edit_tipo_equipamento_path(@tipo_equipamento), class: 'btn' %> |
<%= link_to 'Voltar', tipo_equipamentos_path, class: 'btn' %>