config/routes.rb
Rails.application.routes.draw do
  resources :equipamentos

  get 'equipamentos/autorizar/:id' => 'equipamentos#autorizar', as: 'equipamento_autorizar'
  # namespace :equipamentos do
  #   get 'autorizar'
  #   get 'desaltorizar'
  # end

  resources :tipo_equipamentos
  resources :tipo_documentos

  get 'prazos' => "registroprazos#index"
  get 'prazos/novo' => "registroprazos#new"

  resources :registroprazos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "tipo_documentos#home"
end

app/models/tipo_documento.rb
# == Schema Information
#
# Table name: tipo_documentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  ativo      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TipoDocumento < ApplicationRecord

    validates :nome, presence: true, length: { maximum: 255}, uniqueness: true


    #Método que retorna o nome do objeto instanciado
    def to_s
        self.nome
    end

end

app/controllers/tipo_documentos_controller.rb
# == Schema Information
#
# Table name: tipo_documentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  ativo      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TipoDocumentosController < ApplicationController
  before_action :set_tipo_documento, only: [:show, :edit, :update, :destroy]

  # GET /tipo_documentos
  # GET /tipo_documentos.json
  def index
    @tipo_documentos = TipoDocumento.all
  end

  def home

  end

  # GET /tipo_documentos/1
  # GET /tipo_documentos/1.json
  def show
  end

  # GET /tipo_documentos/new
  def new
    @tipo_documento = TipoDocumento.new(ativo: true)
  end

  # GET /tipo_documentos/1/edit
  def edit
  end

  # POST /tipo_documentos
  # POST /tipo_documentos.json
  def create
    @tipo_documento = TipoDocumento.new(tipo_documento_params)

    respond_to do |format|
      if @tipo_documento.save
        format.html { redirect_to tipo_documentos_path, notice: 'Tipo de documento criado com sucesso.' }
        format.json { render :show, status: :created, location: @tipo_documento }
      else
        format.html { render :new }
        format.json { render json: @tipo_documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_documentos/1
  # PATCH/PUT /tipo_documentos/1.json
  def update
    respond_to do |format|
      if @tipo_documento.update(tipo_documento_params)
        format.html { redirect_to tipo_documentos_path, notice: 'Tipo de documento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @tipo_documento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_documentos/1
  # DELETE /tipo_documentos/1.json
  def destroy
    @tipo_documento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_documentos_url, notice: 'Tipo de documento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_documento
      @tipo_documento = TipoDocumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_documento_params
      params.require(:tipo_documento).permit(:nome, :ativo)
    end
end

app/helpers/tipo_documentos_helper.rb
# == Schema Information
#
# Table name: tipo_documentos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  ativo      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TipoDocumentosHelper
end

app/views/tipo_documentos/_form.html.erb
<%= form_with(model: tipo_documento, local: true) do |form| %>
  <% if tipo_documento.errors.any? %>
    <div id="error_explanation">
      <!-- <%# <h2><%= pluralize(tipo_documento.errors.count, "error") %> prohibited this tipo_documento from being saved:</h2> %> -->

      <ul>
      <% tipo_documento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">  
    <%= form.check_box :ativo %>
    <%= form.label :ativo %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar",  class:"btn" %>
  </div>
<% end %>

<% link_to 'Cancelar', tipo_documentos_path %>

app/views/tipo_documentos/edit.html.erb
<h1>Editar tipo de documento</h1>

<%= render 'form', tipo_documento: @tipo_documento %>

<%= link_to 'Visualizar', @tipo_documento, class:"btn" %> |
<%= link_to 'Cancelar', tipo_documentos_path, class:"btn", data: { confirm: "Tem certeza que deseja voltar sem salvar?"} %>

app/views/tipo_documentos/home.html.erb
<h1 class="center-align">SGF</h1>

app/views/tipo_documentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registro de tipo de documento</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_documentos.each do |tipo_documento| %>
      <tr>
        <td><%= tipo_documento %></td>
        <td><%= tipo_documento.ativo == true ? "SIM" : "NÃO" %></td>
        <td><%= link_to 'Visualizar', tipo_documento, class:"btn"%></td>
        <td><%= link_to 'Alterar', edit_tipo_documento_path(tipo_documento), class:"btn" %></td>
        <td><%= link_to 'Excluir', tipo_documento, method: :delete, class:"btn", data: { confirm: "Tem certeza que deseja remover esse tipo de documento '#{tipo_documento.nome}'?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar tipo de documento', new_tipo_documento_path, class:"btn" %>

app/views/tipo_documentos/new.html.erb
<h1>Novo tipo de documento</h1>

<%= render 'form', tipo_documento: @tipo_documento %>

<%= link_to 'Cancelar', tipo_documentos_path, class:"btn", data: { confirm: "Tem certeza que deseja voltar sem salvar?"}%>

app/views/tipo_documentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tipo_documento.nome %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @tipo_documento.ativo %>
</p>

<%= link_to 'Editar', edit_tipo_documento_path(@tipo_documento), class:"btn" %> |
<%= link_to 'Voltar', tipo_documentos_path, class:"btn" %>