config/routes.rb
Rails.application.routes.draw do
  resources :equipamentos

  get 'equipamentos/autorizar/:id' => 'equipamentos#autorizar', as: 'equipamento_autorizar'
  # namespace :equipamentos do
  #   get 'autorizar'
  #   get 'desaltorizar'
  # end

  resources :tipo_equipamentos
  resources :tipo_documentos

  get 'prazos' => "registroprazos#index"
  get 'prazos/novo' => "registroprazos#new"

  resources :registroprazos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "tipo_documentos#home"
end

app/models/registroprazo.rb
# == Schema Information
#
# Table name: registroprazos
#
#  id         :bigint           not null, primary key
#  contador   :string
#  descricao  :string
#  namespace  :string
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Registroprazo < ApplicationRecord
end

app/controllers/registroprazos_controller.rb
# == Schema Information
#
# Table name: registroprazos
#
#  id         :bigint           not null, primary key
#  contador   :string
#  descricao  :string
#  namespace  :string
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RegistroprazosController < ApplicationController
  before_action :set_registroprazo, only: [:show, :edit, :update, :destroy]

  # GET /registroprazos
  # GET /registroprazos.json
  def index
    @registroprazos = Registroprazo.all
  end

  # GET /registroprazos/1
  # GET /registroprazos/1.json
  def show
  end

  # GET /registroprazos/new
  def new
    @registroprazo = Registroprazo.new
  end

  # GET /registroprazos/1/edit
  def edit
  end

  # POST /registroprazos
  # POST /registroprazos.json
  def create
    @registroprazo = Registroprazo.new(registroprazo_params)

    respond_to do |format|
      if @registroprazo.save
        format.html { redirect_to @registroprazo, notice: 'Registroprazo was successfully created.' }
        format.json { render :show, status: :created, location: @registroprazo }
      else
        format.html { render :new }
        format.json { render json: @registroprazo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registroprazos/1
  # PATCH/PUT /registroprazos/1.json
  def update
    respond_to do |format|
      if @registroprazo.update(registroprazo_params)
        format.html { redirect_to @registroprazo, notice: 'Registroprazo was successfully updated.' }
        format.json { render :show, status: :ok, location: @registroprazo }
      else
        format.html { render :edit }
        format.json { render json: @registroprazo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registroprazos/1
  # DELETE /registroprazos/1.json
  def destroy
    @registroprazo.destroy
    respond_to do |format|
      format.html { redirect_to registroprazos_url, notice: 'Registroprazo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registroprazo
      @registroprazo = Registroprazo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registroprazo_params
      params.require(:registroprazo).permit(:nome, :descricao, :contador, :namespace)
    end
end

app/helpers/registroprazos_helper.rb
# == Schema Information
#
# Table name: registroprazos
#
#  id         :bigint           not null, primary key
#  contador   :string
#  descricao  :string
#  namespace  :string
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module RegistroprazosHelper
end

app/views/registroprazos/_form.html.erb
<%= form_with(model: registroprazo, local: true) do |form| %>
  <% if registroprazo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registroprazo.errors.count, "error") %> prohibited this registroprazo from being saved:</h2>

      <ul>
      <% registroprazo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :contador %>
    <%= form.select :contador, ['Dia', 'Mês', 'Ano'] %>
  </div>

  <div class="field">
    <%= form.label :namespace %>
    <%= form.text_field :namespace %>
  </div>

  <div class="actions">
    <%= form.submit value: "Salvar", class: "waves-effect waves-light btn"%>
  </div>
<% end %>

<style type="text/css">
  .waves-button-input{
    margin-top: 14% !important;
  }
</style>

app/views/registroprazos/edit.html.erb
<h1>Editing Registroprazo</h1>

<%= render 'form', registroprazo: @registroprazo %>

<%= link_to 'Show', @registroprazo, class: "waves-effect waves-light btn" %> |
<%= link_to 'Back', registroprazos_path, class: "waves-effect waves-light btn" %>

app/views/registroprazos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prazos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Contador</th>
      <th>Namespace</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registroprazos.each do |registroprazo| %>
      <tr>
        <td><%= registroprazo.nome %></td>
        <td><%= registroprazo.descricao %></td>
        <td><%= registroprazo.contador %></td>
        <td><%= registroprazo.namespace %></td>
        <td><%= link_to 'Show', registroprazo, class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Edit', edit_registroprazo_path(registroprazo), class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', registroprazo, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to icon('add'), new_registroprazo_path , class: "waves-effect waves-light btn", href:"prazos/novo"%>

app/views/registroprazos/new.html.erb
<h1>Novo Prazo</h1>

<%= render 'form', registroprazo: @registroprazo, class: "waves-effect waves-light btn" %>

<%= link_to 'Back', registroprazos_path, class: "waves-effect waves-light btn" %>

app/views/registroprazos/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Novo Prazo</span>
	          	<p>
				  <strong>Nome:</strong>
				  <%= @registroprazo.nome %>
				</p>
				<p>
				  <strong>Descricao:</strong>
				  <%= @registroprazo.descricao %>
				</p>
				<p>
				  <strong>Contador:</strong>
				  <%= @registroprazo.contador %>
				</p>
				<p>
				  <strong>Namespace:</strong>
				  <%= @registroprazo.namespace %>
				</p>
        </div>
        <div class="card-action">

         	<%= link_to icon('edit'), edit_registroprazo_path(@registroprazo), class: "waves-effect waves-light btn" %> 
			<%= link_to icon('check'), registroprazos_path, class: "waves-effect waves-light btn" %>
        </div>
      </div>
    </div>
  </div>
           